#get all notifications
###
GET http://localhost:8000/api/notifications/getallnotifications HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDg1ZjMyMTg4MzRmNTIzN2I0ZTkyZDciLCJmaXJzdG5hbWUiOiJzYW1lZXIiLCJsYXN0bmFtZSI6Imthcm4iLCJ1c2VybmFtZSI6InNhbWVlci5rYXJuQGVkdS5zYXZvbmlhLmZpIiwiYXZhdGFyIjoiaHR0cHM6Ly9pLnBpbmltZy5jb20vNTY0eC81YS8xYy84Ni81YTFjODZlYzRmYWQzNzM5ZGZlNjUzNDMxN2NjYWNkMi5qcGciLCJpc0FkbWluIjoic3R1ZGVudCIsImlhdCI6MTY4ODIwNzc5MX0.3VqMW2Wf9yY38Qh6HBnuW9ZLnXZ3RFm3n1JKoSVuFwk

#get email count
###
GET http://localhost:8000/api/notifications/getemailcount HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDg1ZjMyMTg4MzRmNTIzN2I0ZTkyZDciLCJmaXJzdG5hbWUiOiJzYW1lZXIiLCJsYXN0bmFtZSI6Imthcm4iLCJ1c2VybmFtZSI6InNhbWVlci5rYXJuQGVkdS5zYXZvbmlhLmZpIiwiYXZhdGFyIjoiaHR0cHM6Ly9pLnBpbmltZy5jb20vNTY0eC81YS8xYy84Ni81YTFjODZlYzRmYWQzNzM5ZGZlNjUzNDMxN2NjYWNkMi5qcGciLCJpc0FkbWluIjoic3R1ZGVudCIsImlhdCI6MTY4ODIwNzc5MX0.3VqMW2Wf9yY38Qh6HBnuW9ZLnXZ3RFm3n1JKoSVuFwk

